# Generated by Django 4.1.7 on 2023-03-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='name',
        ),
        migrations.AddField(
            model_name='productsize',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
