# Generated by Django 4.1.7 on 2023-03-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_product_options_orderitem_product_option'),
        ('product', '0002_productitem_created_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductOptions',
            new_name='ProductOption',
        ),
    ]
