# Generated by Django 4.1.7 on 2023-03-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='inventory_total',
        ),
        migrations.AddField(
            model_name='productoption',
            name='inventory_total',
            field=models.IntegerField(default=0),
        ),
    ]
