# Generated by Django 4.1.7 on 2023-03-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productsize_name_productsize_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
