# Generated by Django 4.1.7 on 2023-03-08 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_productoptions_productoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoptioncolor',
            name='product_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='product.productoption'),
        ),
        migrations.AlterField(
            model_name='productoptionsize',
            name='product_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='product.productoption'),
        ),
    ]
