# Generated by Django 4.1.7 on 2023-03-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productsize_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='product_variants_colors', to='product.productcolor'),
        ),
    ]
