# Generated by Django 4.1.7 on 2023-03-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productimage_product_alter_productvariant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='primary_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
