# Generated by Django 4.1.7 on 2023-03-17 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productsize_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoccerJersey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_type', models.CharField(choices=[('CLUB', 'Club'), ('NATIONAL_TEAM', 'National Team')], default='CLUB', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SoccerPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('logo_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SoccerPlayerJersey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('jersey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jersey_players', to='product.soccerjersey')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_jerseys', to='product.soccerplayer')),
            ],
        ),
        migrations.AddField(
            model_name='soccerjersey',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jerseys', to='product.team'),
        ),
        migrations.AddField(
            model_name='product',
            name='soccerplayerjersey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.soccerplayerjersey'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='product.tag'),
        ),
    ]
