# Generated by Django 4.1.7 on 2023-03-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_soccerjersey_soccerplayer_tag_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('CLUB', 'Club'), ('NATIONAL_TEAM', 'National Team')], default='CLUB', max_length=50),
        ),
    ]
