# Generated by Django 4.1.7 on 2023-03-17 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_team_team_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soccerjersey',
            name='name',
        ),
    ]
