# Generated by Django 4.1.7 on 2023-03-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_soccerjersey_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soccerplayerjersey',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soccerplayerjersey',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_jerseys', to='product.soccerplayer'),
        ),
    ]
