import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Inter,
  Plus_Jakarta_Sans,
  Space_Grotesk,
} from "next/font/google";
import "./globals.css";
import Providers from "./provider";
import HeaderContainer from "@/Components/Header/Header";
import NotificationBar from "@/Components/NotificationBar/NotificationBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

export const fontHead = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-head",
  display: "swap",
});

export const fontNum = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-num",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fontSans.variable} ${fontHead.variable} ${fontNum.variable} min-h-dvh bg-slate-50 text-slate-900 antialiased`}
      >
        <Providers>
          <NotificationBar notification="✨ New: Spring deals live now. Free returns within 30 days." />
          <HeaderContainer />
          {children}
        </Providers>
      </body>
    </html>
  );
}
