# Generated by Django 4.1.7 on 2023-03-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_options',
            new_name='product_option',
        ),
    ]
